version: '2.0'
services:
  frontend:
    image: myfrontend
    build:
      context: frontend
      dockerfile: Dockerfile
      # args:
      #   ip: ${IP_V4}
    ports:
      - 8081:3000
    # environment:
    #   - IP_ADDRESS=${IP_V4}
    #   - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
  backend:
    image: mybackend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    # environment:
    #   - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}