# version: '2.0'
# services:
#   frontend:
#     image: myfrontend
#     build:
#       context: frontend
#       dockerfile: Dockerfile
#       # args:
#       #   ip: ${IP_V4}
#     ports:
#       - 8081:3000
#     # environment:
#     #   - IP_ADDRESS=${IP_V4}
#     #   - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
#   backend:
#     image: mybackend
#     build:
#       context: backend
#       dockerfile: Dockerfile
#     ports:
#       - 8080:8080
#     # environment:
#     #   - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}

version: '3.8'
services:
  frontend:
    container_name: tictactoe-frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        - frontend_port=${FRONTEND_PORT}
        - backend_port=${BACKEND_PORT}
        - ip=${IP_V4}
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - IP_ADDRESS=${IP_V4}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    networks:
      - tictactoe_network

  backend:
    container_name: tictactoe-backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    networks:
      - tictactoe_network

networks:
  tictactoe_network:
    driver: bridge
